name: Run Scanner

on:
  schedule:
    - cron: "*/1 4-10 * * 1-5"  # IST 9:15–15:30 approx
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install deps
        run: pip install requests

      - name: Run script
        run: python scanner.py
